# Generated by Django 4.2.5 on 2023-09-28 08:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubscription',
            name='end_date',
        ),
        migrations.AddField(
            model_name='subscription',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(days=31)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscription',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='title',
            field=models.CharField(max_length=256, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='start_date',
            field=models.DateField(verbose_name='Начало'),
        ),
    ]
