# Generated by Django 4.2.5 on 2023-09-27 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe_image_alter_ingredient_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='calories',
            field=models.IntegerField(blank=True, null=True, verbose_name='Калорийность (ккал)'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='guide',
            field=models.TextField(blank=True, verbose_name='Инструкция'),
        ),
    ]
