# Generated by Django 4.2.5 on 2023-09-28 10:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0005_recipe_dislikes'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='is_teaser',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='disliked_recipes', to=settings.AUTH_USER_MODEL, verbose_name='Кто не любит (ID пользователей)'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_recipes', to=settings.AUTH_USER_MODEL, verbose_name='Кто любит (ID пользователей)'),
        ),
    ]
