# Generated by Django 4.2.5 on 2023-09-28 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_recipe_is_teaser_alter_recipe_dislikes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='is_teaser',
            field=models.BooleanField(verbose_name='Показывать в превью'),
        ),
    ]
