# Generated by Django 4.2.5 on 2023-09-29 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_telegramaccount_id_and_more'),
        ('recipes', '0007_alter_recipe_is_teaser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='FoodPlan',
            fields=[
                ('tg_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='food_plan', serialize=False, to='accounts.telegramaccount', verbose_name='Telegram ID')),
                ('preferences', models.ManyToManyField(related_name='food_plans', to='recipes.preference', verbose_name='Предпочтения')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='preferences',
            field=models.ManyToManyField(related_name='recipes', to='recipes.preference', verbose_name='Предпочтения'),
        ),
    ]
