# Generated by Django 4.2.5 on 2023-10-01 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_telegramaccount_id_and_more'),
        ('recipes', '0008_preference_foodplan_recipe_preferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='disliked_recipes', to='accounts.telegramaccount', verbose_name='Кто не любит (ID пользователей)'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_recipes', to='accounts.telegramaccount', verbose_name='Кто любит (ID пользователей)'),
        ),
    ]
