# Generated by Django 4.2.5 on 2023-10-01 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_rename_user_payment_tg_account'),
        ('recipes', '0009_alter_recipe_dislikes_alter_recipe_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodplan',
            name='recipes_count',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='foodplan',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Начало'),
        ),
        migrations.AddField(
            model_name='foodplan',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food_plans', to='subscriptions.subscription'),
        ),
    ]
